name: PlayerWarps
main: me.wiefferink.playerwarps.PlayerWarps
version: 1.0
commands:
  warp:
    description: Display help (all possible commands)
    usage: /warp
    aliases: [wr,warps]
  sethome:
    description: Add a warp
  home:
    description: Go to a warp
  delhome:
    description: Delete a warp
permissions:
  playerwarps.*:
    description: Give access to all commands of PlayerWarps
    children:
      playerwarps.help: true
      playerwarps.limits.unlimited: true
      playerwarps.limits.default: false
      playerwarps.to: true
      playerwarps.topublic: true
      playerwarps.toprivate: true
      playerwarps.add: true
      playerwarps.addother: true
      playerwarps.del: true
      playerwarps.delother: true
      playerwarps.trust: true
      playerwarps.trustother: true
      playerwarps.untrust: true
      playerwarps.untrustother: true
      playerwarps.list: true
      playerwarps.listother: true
      playerwarps.public: true
      playerwarps.info: true
      playerwarps.infoprivate: true
      playerwarps.infopublic: true
      playerwarps.tabcomplete: true
      playerwarps.reload: true
  playerwarps.help:
    description: Allows you to see the help pages
    default: true
  playerwarps.limits.default:
    description: Default limits for creating warps
    default: not op
  playerwarps.limits.unlimited:
    description: Unlimited for OP's as default
    default: op
  playerwarps.to:
    description: Warp to a warp from yourself
    default: true
  playerwarps.topublic:
    description: Warp to a public warp from another player
    default: true
  playerwarps.toprivate:
    description: Warp to a private warp from another player
    default: op
  playerwarps.add:
    description: Add a warp (public and private)
    default: true
  playerwarps.addother:
    description: Add a warp for another player
    default: op
  playerwarps.del:
    description: Delete a warp from yourself
    default: true
  playerwarps.delother:
    description: Delete a warp for another player
    default: op
  playerwarps.list:
    description: List your warps
    default: true
  playerwarps.listother:
    description: List warps of another player
    default: op
  playerwarps.public:
    description: List public warps
    default: true
  playerwarps.trust:
    description: Trust a player for a warp from yourself
    default: true
  playerwarps.trustother:
    description: Trust a player for a warp from another player
    default: op
  playerwarps.untrust:
    description: Untrust a player for a warp from yourself
    default: true
  playerwarps.untrustother:
    description: Untrust a player for a warp from another player
    default: op
  playerwarps.info:
    description: Display info about warps
    default: true
  playerwarps.infoprivate:
    description: Display info about private warps from other players
    default: op
  playerwarps.infopublic:
    description: Display info about public warps from other players
    default: true
  playerwarps.tabcomplete:
    description: Tab complete commands
    default: true
  playerwarps.reload:
    description: Reloads the plugin
    default: op
